// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa4CBr-7aFc7XSaq6IjjV5GrFC6CKcSeU',
    appId: '1:310861269869:web:42e3d110da41b266342864',
    messagingSenderId: '310861269869',
    projectId: 'news-card-screen',
    authDomain: 'news-card-screen.firebaseapp.com',
    storageBucket: 'news-card-screen.appspot.com',
    measurementId: 'G-16TS7CEMFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xPvU21J5MXcbLiwk-oL0Vu13QDtwTNw',
    appId: '1:310861269869:android:0ddb17299f862afd342864',
    messagingSenderId: '310861269869',
    projectId: 'news-card-screen',
    storageBucket: 'news-card-screen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL-2pSIKBsEoL5E5TIuSy_h4Mm9UUU4R8',
    appId: '1:310861269869:ios:bfa30946fdf4c0cd342864',
    messagingSenderId: '310861269869',
    projectId: 'news-card-screen',
    storageBucket: 'news-card-screen.appspot.com',
    iosBundleId: 'com.example.newsCardScreen',
  );
}
